      SUBROUTINE VTINLB (RPNT,IEDG,ITRI,RWRK,IWRK)
C
      DIMENSION RPNT(*),IEDG(*),ITRI(*),RWRK(*),IWRK(*)
C
C VTINLB generates the informational label; the quantities defining the
C label are added to the lists in real workspaces 3 and 4.
C
C
C Declare all of the VASPACKT common blocks.
C
C
C VTCOM1 contains integer and real variables.
C
      COMMON /VTCOM1/ AHAW,AHLN,AHLR,AHSP,AHSR
      COMMON /VTCOM1/ ANIL,ANM1,ANM2,ANZF,AVEL,CHWM,CXIL,CXZF
      COMMON /VTCOM1/ CYIL,CYZF,DCNU,DCNV,DCNW,DMAX
      COMMON /VTCOM1/ DMIN,DVAL  !  REUSE FOR FLOWMIN AND FLOWMAX?
      COMMON /VTCOM1/ EMAX,EPSI
      COMMON /VTCOM1/ IBIL,IBZF,ICIL,ICLR(255)
      COMMON /VTCOM1/ ICSG,ICST,ICTT,ICTV,ICZF,IDBG,IISP
      COMMON /VTCOM1/ IIWS(2),IIWU,ILBC,IMPF
      COMMON /VTCOM1/ INIL  !  NEEDED? (INFORMATIONAL LABEL INDEX)
      COMMON /VTCOM1/ INIT,IPAI,IPIS
      COMMON /VTCOM1/ IPIL,IPZF,IRNG,IRWS(2),IRWU,ISET,ISTA(625)
      COMMON /VTCOM1/ ISVT,ITBM,IWSO,IZFF,JODP,JOMA
      COMMON /VTCOM1/ JOTZ,LCTM,LEA1,LEA2,LEA3,LEE1,LEE2,LEE3
      COMMON /VTCOM1/ LIWB,LIWK,LIWS(2),LNLG
      COMMON /VTCOM1/ LOEN,LOPN,LOTN
      COMMON /VTCOM1/ LRWK,LRWS(2)
      COMMON /VTCOM1/ LSDD,LSDL,LSDM,LTIL,LTZF,MIRO,NCLR
      COMMON /VTCOM1/ NDGL,NEDG,NEXL,NEXT,NEXU
      COMMON /VTCOM1/ NLBS  !  NEEDED? (NUMBER OF LABELS)
      COMMON /VTCOM1/ NLSD,NLZF,NOMF,NPNT
      COMMON /VTCOM1/ NR04  !  NEEDED? (LABEL-LIST MANAGEMENT)
      COMMON /VTCOM1/ NSDL,NSDR,NTRI,OORV,PCPX,PCPY,PCPZ
      COMMON /VTCOM1/ PITH  !  NEEDED? (STREAMLINE INTERPOLATION)
      COMMON /VTCOM1/ SCFS,SCFU  !  NEEDED? (SCALE FACTORS)
      COMMON /VTCOM1/ SLLN,SLLR,SLPS,SLPR,SLSP,SLSR,SVSP,SVSR
      COMMON /VTCOM1/ TTLL,TTLR,TTSP,TTSR,TVAL(0:256)
      COMMON /VTCOM1/ UVPB,UVPL,UVPR,UVPS,UVPT,UWDB,UWDL
      COMMON /VTCOM1/ UWDR,UWDT,VFRA,VRLN,VRLR,VRMG,VRMR
      COMMON /VTCOM1/ VVMM
      COMMON /VTCOM1/ WCIL,WCZF,WLIL,WLZF
      COMMON /VTCOM1/ WWIL,WWZF
      COMMON /VTCOM1/ XLBC,XMAX,XMIN,XVPL,XVPR,XWDL,XWDR
      COMMON /VTCOM1/ YLBC,YMAX,YMIN,YVPB,YVPT,YWDB,YWDT,ZMAX,ZMIN
C
      EQUIVALENCE (IIWS(1),II01),(LIWS(1),LI01)
      EQUIVALENCE (IIWS(2),II02),(LIWS(2),LI02)
      EQUIVALENCE (IRWS(1),IR01),(LRWS(1),LR01)
      EQUIVALENCE (IRWS(2),IR02),(LRWS(2),LR02)
      SAVE   /VTCOM1/
C
C VTCOM2 holds character parameters.
C
      COMMON /VTCOM2/ CHEX,CTMA,CTMB,FRMT
      COMMON /VTCOM2/ TXIL,TXZF
      CHARACTER*13 CHEX
      CHARACTER*500 CTMA,CTMB
      CHARACTER*8 FRMT
      CHARACTER*128 TXIL
      CHARACTER*64 TXZF
      SAVE   /VTCOM2/
C
C If the text string for the informational label is blank, do nothing.
C
      IF (TXIL(1:LTIL).EQ.' ') RETURN
C
C Otherwise, form the informational label ...
C
      CALL VTSBST (TXIL(1:LTIL),CTMA,LCTM)
C
C ... get sizing information for the label ...
C
      XPFS=XVPL+CXIL*(XVPR-XVPL)
      YPFS=YVPB+CYIL*(YVPT-YVPB)
      XLBC=CFUX(XPFS)
      IF (ICFELL('VTINLB',1).NE.0) RETURN
      YLBC=CFUY(YPFS)
      IF (ICFELL('VTINLB',2).NE.0) RETURN
      WCFS=CHWM*WCIL*(XVPR-XVPL)
      WWFS=CHWM*WWIL*(XVPR-XVPL)
C
      CALL PCGETI ('TE',ISTE)
      IF (ICFELL('VTINLB',3).NE.0) RETURN
      CALL PCSETI ('TE',1)
      IF (ICFELL('VTINLB',4).NE.0) RETURN
      CALL HLUVTCHIL (+1)
      IF (ICFELL('VTINLB',5).NE.0) RETURN
      IF (CTMA(1:LCTM).EQ.' ') GO TO 101
      CALL PLCHHQ (XLBC,YLBC,CTMA(1:LCTM),WCFS,360.,0.)
      IF (ICFELL('VTINLB',6).NE.0) RETURN
      CALL HLUVTCHIL (-1)
      IF (ICFELL('VTINLB',7).NE.0) RETURN
      CALL PCGETR ('DL',DSTL)
      IF (ICFELL('VTINLB',8).NE.0) RETURN
      CALL PCGETR ('DR',DSTR)
      IF (ICFELL('VTINLB',9).NE.0) RETURN
      CALL PCGETR ('DB',DSTB)
      IF (ICFELL('VTINLB',10).NE.0) RETURN
      CALL PCGETR ('DT',DSTT)
      IF (ICFELL('VTINLB',11).NE.0) RETURN
      CALL PCSETI ('TE',ISTE)
      IF (ICFELL('VTINLB',12).NE.0) RETURN
      DSTL=DSTL+WWFS
      DSTR=DSTR+WWFS
      DSTB=DSTB+WWFS
      DSTT=DSTT+WWFS
C
C ... and then put information about the label into the lists.
C
      SINA=SIN(.017453292519943*ANIL)
      COSA=COS(.017453292519943*ANIL)
C
      IXPO=MOD(IPIL+4,3)-1
C
      IF (IXPO.LT.0) THEN
        XPFS=XPFS+DSTL*COSA
        YPFS=YPFS+DSTL*SINA
      ELSE IF (IXPO.GT.0) THEN
        XPFS=XPFS-DSTR*COSA
        YPFS=YPFS-DSTR*SINA
      END IF
C
      IYPO=(IPIL+4)/3-1
C
      IF (IYPO.LT.0) THEN
        XPFS=XPFS-DSTB*SINA
        YPFS=YPFS+DSTB*COSA
      ELSE IF (IYPO.GT.0) THEN
        XPFS=XPFS+DSTT*SINA
        YPFS=YPFS-DSTT*COSA
      END IF
C
      XLBC=CFUX(XPFS)
      IF (ICFELL('VTINLB',13).NE.0) RETURN
      YLBC=CFUY(YPFS)
      IF (ICFELL('VTINLB',14).NE.0) RETURN
C
      NLBS=NLBS+1
      IF (4*NLBS.GT.LR03) THEN
        CALL VTGRWS (RWRK,3,MAX(4*NLBS,LR03+100),IWSE)
        IF (IWSE.NE.0.OR.ICFELL('VTINLB',15).NE.0) THEN
          NLBS=NLBS-1
          RETURN
        END IF
      END IF
      RWRK(IR03+4*(NLBS-1)+1)=XPFS
      RWRK(IR03+4*(NLBS-1)+2)=YPFS
      RWRK(IR03+4*(NLBS-1)+3)=.017453292519943*ANIL
      RWRK(IR03+4*(NLBS-1)+4)=-NR04
      NR04=NR04+6
      IF (NR04.GT.LR04) THEN
        CALL VTGRWS (RWRK,4,MAX(NR04,LR04+100),IWSE)
        IF (IWSE.NE.0.OR.ICFELL('VTINLB',16).NE.0) THEN
          NLBS=NLBS-1
          RETURN
        END IF
      END IF
      RWRK(IR04+NR04-5)=0.
      RWRK(IR04+NR04-4)=0.
      RWRK(IR04+NR04-3)=DSTL
      RWRK(IR04+NR04-2)=DSTR
      RWRK(IR04+NR04-1)=DSTB
      RWRK(IR04+NR04  )=DSTT
C
C Done.
C
  101 RETURN
C
      END
