      SUBROUTINE VTRSET
C
C This subroutine may be called to reset all variables which have
C default values to those values.
C
C Declare all of the VASPACKT common blocks.
C
C
C VTCOM1 contains integer and real variables.
C
      COMMON /VTCOM1/ AHAW,AHLN,AHLR,AHSP,AHSR
      COMMON /VTCOM1/ ANIL,ANM1,ANM2,ANZF,AVEL,CHWM,CXIL,CXZF
      COMMON /VTCOM1/ CYIL,CYZF,DCNU,DCNV,DCNW,DMAX
      COMMON /VTCOM1/ DMIN,DVAL  !  REUSE FOR FLOWMIN AND FLOWMAX?
      COMMON /VTCOM1/ EMAX,EPSI
      COMMON /VTCOM1/ IBIL,IBZF,ICIL,ICLR(255)
      COMMON /VTCOM1/ ICSG,ICST,ICTT,ICTV,ICZF,IDBG,IISP
      COMMON /VTCOM1/ IIWS(2),IIWU,ILBC,IMPF
      COMMON /VTCOM1/ INIL  !  NEEDED? (INFORMATIONAL LABEL INDEX)
      COMMON /VTCOM1/ INIT,IPAI,IPIS
      COMMON /VTCOM1/ IPIL,IPZF,IRNG,IRWS(2),IRWU,ISET,ISTA(625)
      COMMON /VTCOM1/ ISVT,ITBM,IWSO,IZFF,JODP,JOMA
      COMMON /VTCOM1/ JOTZ,LCTM,LEA1,LEA2,LEA3,LEE1,LEE2,LEE3
      COMMON /VTCOM1/ LIWB,LIWK,LIWS(2),LNLG
      COMMON /VTCOM1/ LOEN,LOPN,LOTN
      COMMON /VTCOM1/ LRWK,LRWS(2)
      COMMON /VTCOM1/ LSDD,LSDL,LSDM,LTIL,LTZF,MIRO,NCLR
      COMMON /VTCOM1/ NDGL,NEDG,NEXL,NEXT,NEXU
      COMMON /VTCOM1/ NLBS  !  NEEDED? (NUMBER OF LABELS)
      COMMON /VTCOM1/ NLSD,NLZF,NOMF,NPNT
      COMMON /VTCOM1/ NR04  !  NEEDED? (LABEL-LIST MANAGEMENT)
      COMMON /VTCOM1/ NSDL,NSDR,NTRI,OORV,PCPX,PCPY,PCPZ
      COMMON /VTCOM1/ PITH  !  NEEDED? (STREAMLINE INTERPOLATION)
      COMMON /VTCOM1/ SCFS,SCFU  !  NEEDED? (SCALE FACTORS)
      COMMON /VTCOM1/ SLLN,SLLR,SLPS,SLPR,SLSP,SLSR,SVSP,SVSR
      COMMON /VTCOM1/ TTLL,TTLR,TTSP,TTSR,TVAL(0:256)
      COMMON /VTCOM1/ UVPB,UVPL,UVPR,UVPS,UVPT,UWDB,UWDL
      COMMON /VTCOM1/ UWDR,UWDT,VFRA,VRLN,VRLR,VRMG,VRMR
      COMMON /VTCOM1/ VVMM
      COMMON /VTCOM1/ WCIL,WCZF,WLIL,WLZF
      COMMON /VTCOM1/ WWIL,WWZF
      COMMON /VTCOM1/ XLBC,XMAX,XMIN,XVPL,XVPR,XWDL,XWDR
      COMMON /VTCOM1/ YLBC,YMAX,YMIN,YVPB,YVPT,YWDB,YWDT,ZMAX,ZMIN
C
      EQUIVALENCE (IIWS(1),II01),(LIWS(1),LI01)
      EQUIVALENCE (IIWS(2),II02),(LIWS(2),LI02)
      EQUIVALENCE (IRWS(1),IR01),(LRWS(1),LR01)
      EQUIVALENCE (IRWS(2),IR02),(LRWS(2),LR02)
      SAVE   /VTCOM1/
C
C VTCOM2 holds character parameters.
C
      COMMON /VTCOM2/ CHEX,CTMA,CTMB,FRMT
      COMMON /VTCOM2/ TXIL,TXZF
      CHARACTER*13 CHEX
      CHARACTER*500 CTMA,CTMB
      CHARACTER*8 FRMT
      CHARACTER*128 TXIL
      CHARACTER*64 TXZF
      SAVE   /VTCOM2/
C
C Check for an uncleared prior error.
C
      IF (ICFELL('VTRSET - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
C
C Reset individual parameters.
C
      AHAW=30.
      AHLN=.04
      AHSP=.16
      ANIL=0.
      ANZF=0.
      AVEL=0.
      CHWM=1.
      CTMA=' '
      CTMB=' '
      CXIL=.98
      CXZF=.50
      CYIL=-.02
      CYZF=.50
      DMAX=0.
      DMIN=0.
      DVAL=0.
      IBIL=0
      IBZF=0
      ICIL=-1
      ICSG=1
      ICST=1
      ICTT=1
      ICTV=0
      ICZF=-1
      IDBG=0
      IISP=0
      IIWU=0
      ILBC=0
      IMPF=0
      INIT=0
      IPAI=0
      IPIL=4
      IPIS=0
      IPZF=0
      IRNG=0
      IRWU=0
      ISET=1
      ISVT=5
      ITBM=1
      IWSO=1
      IZFF=0
      LCTM=1
      LIWB=2500
      LTZF=10
      LTIL=21
      MIRO=0
      NCLR=0
      NEXL=0
      NEXT=1
      NEXU=5
      NLBS=0
      NLSD=1
      NLZF=0
      NOMF=6
      NSDL=4
      OORV=0.
      PCPX=0.
      PCPY=0.
      PCPZ=0.
      PITH=0.
      SCFS=1.
      SCFU=1.
      SLLN=8.
      SLPS=.001
      SLSP=.072
      SVSP=0.
      TTLL=.018
      TTSP=.036
      TXIL='SCALE FACTOR IS $SFU$'
      TXZF='ZERO FIELD'
      UVPL=.05
      UVPR=.95
      UVPB=.05
      UVPT=.95
      UVPS=.25
      UWDL=0.
      UWDR=0.
      UWDB=0.
      UWDT=0.
      VFRA=0.
      VVMM=0.
      VRLN=0.
      VRMG=0.
      WCIL=.012
      WCZF=.012
      WLIL=0.
      WLZF=0.
      WWIL=.005
      WWZF=.005
      XLBC=0.
      XMAX=0.
      XMIN=0.
      YLBC=0.
      YMAX=0.
      YMIN=0.
      ZMAX=0.
      ZMIN=0.
C
C Reset parameter array elements.
C
      DO 10001 I=1,255
        ICLR(I)=1
        TVAL(I)=0.
10001 CONTINUE
      DO 10002 I=1,2
        IIWS(I)=0
        LIWS(I)=0
10002 CONTINUE
      DO 10003 I=1,2
        IRWS(I)=0
        LRWS(I)=0
10003 CONTINUE
C
C Done.
C
      RETURN
C
      END
