      SUBROUTINE VTSLDR (RPNT,IEDG,ITRI,RWRK,IWRK)
C
      DIMENSION RPNT(*),IEDG(*),ITRI(*),RWRK(*),IWRK(*)
C
C This routine draws streamlines.
C
      DIMENSION IAMA(1)
C
      EXTERNAL VTDRPL
C
      DATA IAMA / 0 /
C
C Check for an uncleared prior error.
C
      IF (ICFELL('VTSLDR - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
C
      CALL VTSLDM (RPNT,IEDG,ITRI,RWRK,IWRK,IAMA,VTDRPL)
      IF (ICFELL('VTSLDR',2).NE.0) RETURN
C
      RETURN
C
      END
