      SUBROUTINE MAPBLA (IAMP)
      INTEGER IAMP(*)
      IF (ICFELL('MAPBLA - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
      CALL MDPBLA (IAMP)
      IF (ICFELL('MAPBLA',2).NE.0) RETURN
      RETURN
      END
