      SUBROUTINE MAPITA (XLAT,XLON,IFST,IAMP,IGRP,IDLT,IDRT)
      REAL    XLAT,XLON
      INTEGER IFST,IAMP(*),IGRP,IDLT,IDRT
      IF (ICFELL('MAPITA - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
      CALL MDPITA (DBLE(XLAT),DBLE(XLON),IFST,IAMP,IGRP,IDLT,IDRT)
      IF (ICFELL('MAPITA',2).NE.0) RETURN
      RETURN
      END
