      SUBROUTINE MAPIQA (IAMP,IGRP,IDLT,IDRT)
      INTEGER IAMP(*),IGRP,IDLT,IDRT
      IF (ICFELL('MAPIQA - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
      CALL MDPIQA (IAMP,IGRP,IDLT,IDRT)
      IF (ICFELL('MAPIQA',2).NE.0) RETURN
      RETURN
      END
