      SUBROUTINE MAPLMM (IAM,XCS,YCS,MCS,IAI,IAG,MAI,LPR)
      INTEGER IAM(*),MCS,IAI(*),IAG(*),MAI
      REAL    XCS(*),YCS(*)
      IF (ICFELL('MAPLMM - UNCLEARED PRIOR ERROR',1).NE.0) RETURN
      CALL MDPLMM (IAM,XCS,YCS,MCS,IAI,IAG,MAI,LPR)
      IF (ICFELL('MAPLMM',2).NE.0) RETURN
      RETURN
      END
